events
{

}

http
{
	server
	{
		listen 443 ssl;
		# listen on port 443 + enable SSL/TLS

		ssl_certificate /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;

		ssl_protocols TLSv1.2 TLSv1.3;

		server_name ytlidi.42.fr;

		root /var/www/html;
		# serve files from /var/www/html
		index index.php index.html;
		# if someone requests / first look for index.php then index.html

		location /
		{
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$
		# if the requested file of the form *.php
		{
			include fastcgi_params;
			# nginx loads information like request mode, query string, client IP from the buil-in file fastcgi_params
			fastcgi_pass wordpress:9000;
			# whenever nginx receive a PHP file, send it to the container named wordpress on port 9000 
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			# tell PHP-FPM the full path of the PHP file to execute
			# $document_root = /var/www/html
			# $fastcgi_script_name = /index.php
		}
	}
}